plugins:
  - jekyll-feed
title: Albo Pretorio Monterotondo
description: Feed RSS ufficiale
url: https://servizionline.hspromilaprod.hypersicapp.net/cmsmonterotondo/portale/albopretorio/albopretorioconsultazione.aspx?P=400
