name: Aggiorna Feed RSS
on:
  schedule:
    - cron: '0 8 * * *'  # Ogni giorno alle 8:00 UTC
  workflow_dispatch:  # Permette l'esecuzione manuale

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install feedgen
      
      - name: Verifica la struttura delle directory e dei file
        run: |
          echo "Directory corrente: $(pwd)"
          echo "Contenuto directory corrente:"
          ls -la
          echo "Verifico esistenza del CSV:"
          ls -la | grep .csv || echo "Nessun file CSV trovato"
      
      - name: Genera feed RSS
        run: |
          python generate_feed.py
          echo "Dopo l'esecuzione dello script:"
          ls -la
      
      - name: Prepara directory per GH Pages
        run: |
          mkdir -p docs
          # Cerca il file feed.xml nella directory corrente o nelle sottodirectory
          FILE_PATH=$(find . -name "feed.xml" -type f | head -n 1)
          
          if [ -n "$FILE_PATH" ]; then
            echo "File trovato: $FILE_PATH"
            cp "$FILE_PATH" docs/
            
            # Cerca anche feed_atom.xml nella stessa directory
            ATOM_PATH="${FILE_PATH/feed.xml/feed_atom.xml}"
            if [ -f "$ATOM_PATH" ]; then
              cp "$ATOM_PATH" docs/
            fi
          else
            echo "File feed.xml non trovato!"
            exit 1
          fi
      
      - name: Commit e push dei file generati
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --staged --quiet || git commit -m "Aggiorna feed RSS: ${{ github.run_id }}"
          git push
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          full_commit_message: "Deploy feed: ${{ github.run_id }}"
