name: Aggiorna Feed RSS
on:
  schedule:
    - cron: '0 8 * * *'  # Ogni giorno alle 8:00 UTC
  workflow_dispatch:  # Permette l'esecuzione manuale

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install feedgen
      
      - name: Genera feed RSS
        run: python generate_feed.py
      
      - name: Prepara directory per GH Pages
        run: |
          mkdir -p docs
          cp feed.xml docs/
          cp feed_atom.xml docs/ || true  # Non fallire se questo file non esiste
      
      - name: Commit e push dei file generati
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add feed.xml docs/
          git diff --staged --quiet || git commit -m "Aggiorna feed RSS: ${{ github.run_id }}"
          git push
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          full_commit_message: "Deploy feed: ${{ github.run_id }}"
