name: Aggiorna Feed RSS
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Scarica dati CSV
        run: wget https://comune.monterotondo.rm.it/albo.csv -O albo.csv
      - name: Genera feed RSS
        run: python generate_feed.py
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
